"""empty message

Revision ID: 3a1aabd133bb
Revises: 0380e8ec69c0
Create Date: 2023-02-13 16:48:36.500153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a1aabd133bb'
down_revision = '0380e8ec69c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('is_del', sa.Boolean(), nullable=True, comment='是否删除'))
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.drop_column('blog', 'is_del')
    # ### end Alembic commands ###
